runtime: python39
entrypoint: gunicorn -b :$PORT main:app

manual_scaling:
  instances: 1

resources:
  cpu: 2  # Increased CPU allocation to 2 cores
  memory_gb: 2  # Increased memory allocation to 2 GB
  disk_size_gb: 20  # Increased disk size to 20 GB
