runtime: python
env: flex
entrypoint: gunicorn -b 0.0.0.0:8080 main:server

runtime_config:
  python_version:3.9

manual_scaling:
  min_instances: 1
  max_instances: 5  # Increased maximum number of instances to 5
  idle_timeout: 20m

resources:
  cpu: 2  # Increased CPU allocation to 2 cores
  memory_gb: 2  # Increased memory allocation to 2 GB
  disk_size_gb: 20  # Increased disk size to 20 GB
